### PR TITLE
Update workflow, add MIT License

### PR DESCRIPTION
**Pull request by sappelhoff**
Thought I'd send an update to this :)

~~unfortunately it fails with~~

~~>   {dpss requires Signal Processing Toolbox.~~

~~https://github.com/sappelhoff/matprep_artifacts/actions/runs/12037815775/job/33562095751#step:6:160~~

~~Did you encounter this problem when you first coded this up @a-hurst ?~~

EDIT: it passes now: https://github.com/sappelhoff/matprep_artifacts/actions/runs/12157766138

### CODE REVIEW

**Comment by a-hurst** [comment]
This looks good to me! My only real comment is, given the intended consistency/stability of these artifacts, whether it makes sense to regularly rebuild with the latest EEGLAB rather than a pinned newer version? Just imagining if an upstream EEGLAB change broke something in MATLAB PREP or caused the numbers to mismatch: is that a problem PyPREP really cares about?

**Comment by sappelhoff** [comment]
I think ideally we would move towards doing the matprep artifacts as part of pypreps CI 🤔 see also https://github.com/sappelhoff/pyprep/issues/160

**Comment by a-hurst** [comment]
@sappelhoff Sorry for the delayed response! Found out at the end of last week that my PhD supervisor is leaving our university for a Dean position halfway across the country which has thrown me and the other members of the lab for a bit of a loop 😓

> I think ideally we would move towards doing the matprep artifacts as part of pypreps CI 🤔 see also [sappelhoff/pyprep#160](https://github.com/sappelhoff/pyprep/issues/160)

Definitely open to this if it makes maintenance easier! I guess you'd need to set up a separate Github Action that generates the artifacts and stores them in a way that can be easily pulled by the unit test scripts?

My only thought re: maintainability is that if the idea is to regularly & automatically regenerate the artefacts using the latest EEGLAB and PREP, it might be useful to have a check of some kind to test the hashes of the artifacts and see whether they've actually changed since last time. Without this, a stray EEGLAB change that ends up breaking MatPREP could cause the artifacts to change and the PyPREP CI to fail and we'd have a hard time pinning down whether it was something we broke or them!

**Comment by sappelhoff** [comment]
> Found out at the end of last week that my PhD supervisor is leaving our university for a Dean position halfway across the country which has thrown me and the other members of the lab for a bit of a loop 😓

oh no, that is tough. How far along are you with your PhD? I hope you will find a solution 😬

> I guess you'd need to set up a separate Github Action that generates the artifacts and stores them in a way that can be easily pulled by the unit test scripts?

I think it will be possible to have this just as a step, and make the following steps depend on the successful completion of that step

> My only thought re: maintainability is that if the idea is to regularly & automatically regenerate the artefacts using the latest EEGLAB and PREP, it might be useful to have a check of some kind to test the hashes of the artifacts and see whether they've actually changed since last time.

This is a good point! We should do exactly that.

---

As for this PR, I pinned the EEGLAB version now, so this is ready for a merge :)

all further plans that we discussed above might have to wait a bit.

**Comment by a-hurst** [comment]
Great, merged!

> oh no, that is tough. How far along are you with your PhD? I hope you will find a solution 😬

Have about a year left! Supervisor says he'll stay a professor emeritus at our current institution so we won't need to find new supervisors and the lab space will stay up and running until we're all done (according to him anyway), but there's still a lot of unknowns ahead. I think I should be fine (done a good chunk of thesis data collection already) but since he's going to be gone by March and will also very busy after (and before) the move we're essentially going to have to learn to run the lab without him.

(Also sorry, tried to respond and somehow ended up editing your comment by mistake! Fixed now)

**Comment by sappelhoff** [comment]
> learn to run the lab without him

having gotten to know you a little bit (online) over the past years, I have a high confidence that you'll make it ;-)

still ... these things happen, but one always hopes not to be in the position oneself. Fingers crossed for you!

**Pull request merged**
